// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB52Hhe77DnPVFN0i9B6eqkhwyEEw7jDuU',
    appId: '1:1095601560572:web:48d5acae64f97f4662b079',
    messagingSenderId: '1095601560572',
    projectId: 'advanced-gbfc-store-app',
    authDomain: 'advanced-gbfc-store-app.firebaseapp.com',
    storageBucket: 'advanced-gbfc-store-app.firebasestorage.app',
    measurementId: 'G-WX7LMSLLSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ5NeSHSHJxBeKzxG2sLXqGt4TM_gU2WE',
    appId: '1:1095601560572:android:48c4998bbdd7710862b079',
    messagingSenderId: '1095601560572',
    projectId: 'advanced-gbfc-store-app',
    storageBucket: 'advanced-gbfc-store-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8f6j0hQA4OE24Mj52cUXI0KphdaNdFpI',
    appId: '1:1095601560572:ios:f0de426454261c7f62b079',
    messagingSenderId: '1095601560572',
    projectId: 'advanced-gbfc-store-app',
    storageBucket: 'advanced-gbfc-store-app.firebasestorage.app',
    iosBundleId: 'com.example.advancedGbfcStoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8f6j0hQA4OE24Mj52cUXI0KphdaNdFpI',
    appId: '1:1095601560572:ios:f0de426454261c7f62b079',
    messagingSenderId: '1095601560572',
    projectId: 'advanced-gbfc-store-app',
    storageBucket: 'advanced-gbfc-store-app.firebasestorage.app',
    iosBundleId: 'com.example.advancedGbfcStoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB52Hhe77DnPVFN0i9B6eqkhwyEEw7jDuU',
    appId: '1:1095601560572:web:eb8916c2d74e7b3062b079',
    messagingSenderId: '1095601560572',
    projectId: 'advanced-gbfc-store-app',
    authDomain: 'advanced-gbfc-store-app.firebaseapp.com',
    storageBucket: 'advanced-gbfc-store-app.firebasestorage.app',
    measurementId: 'G-C0WDGWKDMK',
  );
}
